In [1]:
import numpy as np

In [2]:
import pandas as pd

In [19]:
from scipy import stats

## 1. How likely is it that you roll doubles when rolling two dice?

In [3]:
# 1. Figure out how to represent your data (1 = heads, 0 = tails)
# a dice roll is a random number between 1 and 6

# 2. Create a matrix of random numbers, rows represent simulations cols represent trials
rolls = pd.DataFrame(np.random.randint(1, 7, size=(10000, 2)), columns = ['first','second'])

rolls

first  second
0         4       2
1         2       1
2         6       6
3         5       1
4         6       4
...     ...     ...
9995      3       3
9996      6       5
9997      1       2
9998      6       3
9999      3       2

[10000 rows x 2 columns]

In [4]:
(rolls['first'] == rolls['second']).sum()/10000

0.1669

In [5]:

# 3. Apply an aggregation row-wise to summarize each simulation (sum for the total number of heads)
two_doubles = rolls.apply(lambda row: row['first']==row['second'], axis=1)

# 4. Apply an aggregation to the resulting 1-d array to come up with a experimental probability (>= 2 heads, mean)
two_doubles.mean()

0.1669

## 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [6]:
rolls = pd.DataFrame(np.random.randint(1, 7, size=(10000, 8)))

rolls

0  1  2  3  4  5  6  7
0     1  3  4  4  4  2  6  1
1     3  1  3  6  2  6  4  4
2     1  3  3  3  3  5  1  4
3     5  2  2  6  4  4  6  3
4     4  5  5  5  6  6  3  1
...  .. .. .. .. .. .. .. ..
9995  3  2  1  3  4  5  2  1
9996  4  5  5  6  6  1  5  1
9997  1  5  1  4  2  4  6  5
9998  3  4  5  2  4  6  3  3
9999  2  6  4  3  1  5  1  2

[10000 rows x 8 columns]

In [7]:
did_we_get_at_least_3_3 = (rolls == 3).sum(axis=1)

did_we_get_at_least_3_3
# 4. Apply an aggregation to the resulting 1-d array to come up with a experimental probability (>= 2 heads, mean)
did_we_get_at_least_3_3.mean()

1.339

## 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [8]:
# 3 A, 1 B, that's the P to get 2 B 

In [9]:
n_trials = 2 # billboards
n_simulations = 10_000 # arbitrary number of sims

data_cohort_sim = np.random.uniform(size=(n_simulations, n_trials)) <= .25

In [10]:
data_cohort_sim

array([[ True, False],
       [False,  True],
       [False, False],
       ...,
       [False, False],
       [ True,  True],
       [False, False]])

In [11]:
n_data_cohort_choose = data_cohort_sim.sum(axis=1)
n_data_cohort_choose

array([1, 1, 0, ..., 0, 2, 0])

In [12]:
two_are_data = n_data_cohort_choose >=2


In [13]:
two_are_data.mean()

0.0637

## 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)



In [76]:
# STD = 1.5 
# x Mean = 3
# restock 17
## What's the p x <= 16.

In [20]:
# we're given average and standard deviation, this tells us we need normal distribution
total_poptarts = 17
n_days = 4

mean = 3
std_dev = 1.5

max_poptarts_per_day = 4

dist = stats.norm(mean, std_dev)

# We start with 17 poptarts at the beginning of the week.
# After 4 days how likely is it that there are still poptarts.

# Probability that no more than 16 poptarts are purchased.
dist.cdf(max_poptarts_per_day) ** (1 / n_days)

0.9298307044439873

In [21]:
purchases = np.random.normal(3, 1.5, size =(10_000, 4)).round()
purchases = np.where(purchases < 0, 0, purchases)
 
(purchases.sum(axis=1)<=16).mean()

0.9265

In [23]:
purchases

array([[4., 4., 4., 3.],
       [3., 2., 1., 3.],
       [1., 6., 5., 3.],
       ...,
       [3., 3., 5., 3.],
       [1., 3., 2., 4.],
       [5., 2., 3., 5.]])

## 5. Compare Heights

Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
Since you have means and standard deviations, you can use np.random.normal to generate observations.
If a man and woman are chosen at random, P(woman taller than man)?

In [13]:
male_height = np.random.normal(178, 8, 10000)

In [14]:
female_height = np.random.normal(170,6,10000)

In [15]:
male_height

array([181.9191097 , 166.51622228, 185.99224178, ..., 175.79300942,
       150.20490282, 175.10982262])

In [16]:
female_height

array([171.02073529, 168.11162148, 170.76127032, ..., 173.17506854,
       165.9955116 , 173.29918996])

In [18]:
(male_height < female_height).mean()

0.2097

## 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

In [83]:
n_trials = 50 
n_simulations = 10_000 

download_sim = np.random.uniform(size=(n_simulations, n_trials)) <= 0.004

In [84]:
download_sim

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [85]:
download_sim_choose = download_sim.sum(axis=1)
download_sim_choose

array([0, 1, 0, ..., 0, 0, 0])

In [86]:
no_one_error = download_sim_choose ==0


In [87]:
no_one_error.mean()

0.8214

## 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

p = 0.7
trail = 3

In [68]:
n_trials = 3
n_simulations = 10_000 

food_truck_sim = np.random.uniform(size=(n_simulations, n_trials)) <= 0.7

In [69]:
food_truck_sim

array([[False,  True,  True],
       [ True,  True, False],
       [ True,  True,  True],
       ...,
       [ True,  True, False],
       [ True, False, False],
       [ True, False,  True]])

In [73]:
food_truck_here = food_truck_sim.sum(axis=1)
food_truck_here

array([2, 2, 3, ..., 2, 1, 2])

In [75]:
no_food_truck = food_truck_here <=0

In [76]:
no_food_truck.mean()

0.0286

## How likely is it that a food truck will show up sometime this week?

In [84]:
n_trials = 5
n_simulations = 10_000 

food_truck_sim = np.random.uniform(size=(n_simulations, n_trials)) <= 0.7

In [85]:
food_truck_here = food_truck_sim.sum(axis=1)
food_truck_here

array([3, 2, 3, ..., 5, 1, 2])

In [92]:
no_food_truck = food_truck_here >= 1

In [93]:
no_food_truck.mean()

0.9974

## 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?



In [3]:
import numpy as np

In [68]:
birthday_23 = np.random.randint(1,365,23)
sorted(birthday_23)

[8,
 22,
 36,
 60,
 72,
 125,
 129,
 150,
 174,
 196,
 206,
 248,
 259,
 280,
 290,
 299,
 308,
 316,
 318,
 321,
 325,
 330,
 342]

In [19]:
if len(np.unique(birthday_23)) == 23:
    print('no same')
else:
    print('shared')

shared


In [61]:
def share_birthday():
    
    birthday_list = np.random.randint(1,365,23)
    if len(np.unique(birthday_list)) == 23:
        return 1
    else:
        return 0

In [63]:
n = 100000
freq_no_two_share_birthday = sum([share_birthday() for i in range(n)])
pro_noshare = freq_no_two_share_birthday/n
pro_noshare

0.49157

In [64]:
1-pro_noshare

0.5084299999999999

In [53]:
birthday_23 = np.random.randint(1,365,23)

In [54]:
birthday_23

array([316, 350, 347, 219, 202, 355, 215, 221, 267, 294, 315, 124, 287,
        52, 298, 204, 222, 302, 232, 292, 259,  20, 337])

In [71]:
for i in birthday_23:
    if len(np.unique(birthday_23)) == 23:
        print('1')
    else:
        print('0')

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


In [ ]:
n = 100000
freq_no_two_share_birthday = sum([share_birthday(40) for i in range(n)])
pro_noshare = freq_no_two_share_birthday/n
pro_noshare