In [2]:
import numpy as np

In [3]:
import pandas as pd

## 1. How likely is it that you roll doubles when rolling two dice?

In [5]:
# 1. Figure out how to represent your data (1 = heads, 0 = tails)
# a dice roll is a random number between 1 and 6

# 2. Create a matrix of random numbers, rows represent simulations cols represent trials
rolls = pd.DataFrame(np.random.randint(1, 7, size=(10000, 2)), columns = ['first','second'])

rolls

first  second
0         4       5
1         5       1
2         2       1
3         4       4
4         2       6
...     ...     ...
9995      5       6
9996      3       2
9997      2       4
9998      6       1
9999      2       3

[10000 rows x 2 columns]

In [10]:
(rolls['first'] == rolls['second']).sum()/10000

0.167

In [11]:

# 3. Apply an aggregation row-wise to summarize each simulation (sum for the total number of heads)
two_doubles = rolls.apply(lambda row: row['first']==row['second'], axis=1)

# 4. Apply an aggregation to the resulting 1-d array to come up with a experimental probability (>= 2 heads, mean)
two_doubles.mean()

0.167

## 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [24]:
rolls = pd.DataFrame(np.random.randint(1, 7, size=(10000, 8)))

rolls

0  1  2  3  4  5  6  7
0     3  2  3  5  5  5  2  1
1     1  2  2  5  1  2  3  6
2     6  1  6  3  5  1  6  2
3     1  4  3  6  3  6  4  5
4     5  2  2  3  3  6  4  4
...  .. .. .. .. .. .. .. ..
9995  6  3  6  3  1  5  4  5
9996  1  6  4  1  6  6  1  3
9997  6  2  3  1  6  4  4  1
9998  6  5  6  5  2  1  6  6
9999  2  5  6  6  2  5  5  5

[10000 rows x 8 columns]

In [25]:
did_we_get_at_least_3_3 = (rolls == 3).sum(axis=1) >= 1

# 4. Apply an aggregation to the resulting 1-d array to come up with a experimental probability (>= 2 heads, mean)
did_we_get_at_least_3_3.mean()

0.7664

## 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [26]:
# 3 A, 1 B, that's the P to get 2 B 

In [68]:
n_trials = 2 # billboards
n_simulations = 10_000 # arbitrary number of sims

data_cohort_sim = np.random.uniform(size=(n_simulations, n_trials)) <= .25

In [69]:
data_cohort_sim

array([[False, False],
       [False, False],
       [ True, False],
       ...,
       [False, False],
       [False,  True],
       [False, False]])

In [70]:
n_data_cohort_choose = data_cohort_sim.sum(axis=1)
n_data_cohort_choose

array([0, 0, 1, ..., 0, 1, 0])

In [73]:
two_are_data = n_data_cohort_choose >=2


In [74]:
two_are_data.mean()

0.065

## 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)



In [76]:
# STD = 1.5 /day
# Mean = 3
# restock 17

In [79]:
np.random.normal(3, 1.5, size =(5,1000))

array([[ 3.7451608 ,  3.87633254,  1.33234585, ...,  0.06902782,
         2.0542258 , -1.14996539],
       [ 1.37308267,  4.21264158,  4.60193848, ...,  3.97844897,
         5.63214727,  3.86115834],
       [ 3.0695329 ,  3.55766325,  0.62784014, ...,  4.13317929,
         4.14818875,  2.8893677 ],
       [ 2.16318627,  1.88466829,  5.08066415, ...,  4.55299773,
         2.70164457,  3.9326609 ],
       [ 4.78801661,  3.57112491,  1.98820689, ...,  3.03774888,
         3.26973832,  1.10072252]])